<a href="https://colab.research.google.com/github/IggyJiggy/CE151_AnilBuddhdev/blob/main/Lab1_2_LinearAlgebraWithNumPy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np
import pandas as pd

In [3]:
# 1) Create Two numpy array of size 3 X 2 and 2 X 3
array1 = np.array([[1, 2, 3],[4, 5, 6]])
array2 = np.array([[-8,-9],[0,1],[-7, -8]])
print(array1)
print(array2)

[[1 2 3]
 [4 5 6]]
[[-8 -9]
 [ 0  1]
 [-7 -8]]


In [4]:
# 2) Randomly Initalize that array
array = np.random.rand(2, 4)
print(array)

[[0.62806923 0.51119924 0.56756236 0.7738276 ]
 [0.28884353 0.57696606 0.44919695 0.20732772]]


In [5]:
# 3) Perform matrix multiplication
mul = np.dot(array1, array2)
print(mul)

[[-29 -31]
 [-74 -79]]


In [6]:
# 4) Perform elementwise matrix multiplication
res = [[0 for x in range(len(array1))] for y in range(len(array2[0]))]

for i in range(len(array1)): 
  for j in range(len(array2[0])): 
    for k in range(len(array2)): 
      res[i][j] += array1[i][k] * array2[k][j]
 
print (res)

[[-29, -31], [-74, -79]]


In [7]:
# 5) Find mean of first matrix
mean = np.mean(array1)
print(mean)

3.5


In [9]:
# 6) Convert Numeric entries(columns) of mtcars.csv to Mean Centered Version
url = 'https://gist.githubusercontent.com/seankross/a412dfbd88b3db70b74b/raw/5f23f993cd87c283ce766e7ac6b329ee7cc2e1d1/mtcars.csv'
main_data = pd.read_csv(url)
del main_data['model']
# meancenter
meancenter = main_data.apply(lambda e: e - e.mean())
print(meancenter.head())

        mpg     cyl        disp       hp  ...      vs       am    gear    carb
0  0.909375 -0.1875  -70.721875 -36.6875  ... -0.4375  0.59375  0.3125  1.1875
1  0.909375 -0.1875  -70.721875 -36.6875  ... -0.4375  0.59375  0.3125  1.1875
2  2.709375 -2.1875 -122.721875 -53.6875  ...  0.5625  0.59375  0.3125 -1.8125
3  1.309375 -0.1875   27.278125 -36.6875  ...  0.5625 -0.40625 -0.6875 -1.8125
4 -1.390625  1.8125  129.278125  28.3125  ... -0.4375 -0.40625 -0.6875 -0.8125

[5 rows x 11 columns]
